### ISSUE TITLE
整个课程时间有多长（授课+项目）？1周？1.5周？2周？这关系到知识点的挑选

### ISSUE THREAD

**Issue by yellowb** [yellowb/full-stack-web-course#1]
整个课程时间有多长（授课+项目）？1周？1.5周？2周？这关系到知识点的挑选

**Comment by elathen** [comment]
我个人建议整个课程可以分为：初级和进阶俩部份
先不考虑授课时间的长短，最后可以根据时间和目标群体选择那些知识点讲。

**Comment by Aquariuslt** [comment]
关于JavaScript Engineering这一part,根据之前JShelf小组的PPT
我准备了一下可能要讲到的知识点和路线.
下面是一个目录和实际可能会花的时间,如果这样没有什么问题.
我这边可以开始准备一些 要用到的代码教学模板与更新Engineering的PPT了.
P.S. 需要知道前置的JavaWeb相关的授课课程,我这里是根据我在ITA的时候的印象去准备的

Table of Content
##  Evolution of Web Frontend Development. -Web前端开发的演变过程
该篇章是一个序言部分,讲述了前端项目工程进化的一个基本的步骤.
不需要花太多时间,先有一个Road Map的概念.
在后面的实战中,会遵循这个步骤进行简单开发.

第一阶段：库/框架选型
第二阶段：简单构建优化
第三阶段：JS/CSS模块化开发

(该阶段内容应该是1Hour 内)

## Keywords preparation. - 一些关键而必须的的预备知识.
该阶段过一遍基本的工程化工具,环境知识.
务求对关键词有基本的印象.类似ES6,Babel这种,会在后面手动演变过程的时候,再结合实际例子细讲.

- 基本开发环境的安装与搭建.
Node(NPM) + Webpack + Webpack-Dev-Server + IDE.(基本实践)

- Node.js 与 NPM 如果Node.js的课程在前,就不必花时间讲.如果对NPM的包管理概念不太清晰,则讲述NPM常见的命令与package.json的基本解读(有印象即可)

- CommonJS 语法. 即Node.js的语法,包括模块导入导出的基本概念.(基本实践)
- ES6 语法与Babel. 即ES6基本语法(有印象即可) + Babel模块转译的例子(有印象即可)

- Webpack,Webpack Dev Server. 即对市场上流行第几个打包构建工具(webpack,broserify,rollup)等做一个功能概括,举一个例子进行打包.
举例展示webpack强大的打包功能与webpack-dev-server带来的良好的开发体验.
(有印象即可,务求理解学习演变过程的成本带来开发效率的巨大提升的好处)

- Gulp 对市场上几个 任务流管理工具的介绍(有印象即可)

(以上阶段内容讲述与演示实践大概2-3h左右)

## Getting Start step by step.  - 手动手来实践第二步的一些过程
在讲述完第二部分之后, 以以下几种准备好的代码模板 提供给ITA的同学.
边讲边引导操作这部分的内容.

几个Template的顺序如下:

- Pure JavaWeb + HTML + JS/CSS Version (与所讲的框架无关,如果之前的课程是JQuery + Bootstrap,那就以这个为例子)
以学习JavaWeb的时候最基础的JavaWeb 的项目基础

- JavaWeb Template + NPM management 3 party libs
同样的目录结构,更换成使用NPM 管理第三方JavaScript 与 CSS的项目结构

- JavaWeb Server Side + Webpack Build Version
将最原始的前端源代码目录 与Java项目 的源代码目录分离出来
通过CommonJS 语法去编写代码, 然后打包到Java项目的resources文件夹中
(后续Vue|Angular的项目会用ES6)

务求体验到通过Webpack打包的一个过程,有一个基本的构建概念的实际认识.

- JavaWeb Server Side + Webpack Build + Webpack-Dev-Server 
通过Webpack-Dev-Server提供的强大代码热部署功能,体验方便的开发调试过程.

- JavaWeb Server Side + Webpack + Gulp
较接近实际生产项目的,根据项目需求可定制任务构建流的模板.

(以上阶段内容与实践,大概是半天~一天的时间,如果之前讲的内容是Node.js+Express,也可以把JavaWeb Server 无缝更换成Node.js+ Express(KOA))



## Getting Started for AngularJS | VueJS
有了第三部分的基本实战之后,大概就可以根据具体项目具体定制下课程.
该部分的具体内容可能是接下来再细分谁去讲,怎么讲.
但是路线图应该是与第三部的渐进式路线相同.
但是在实战中的不同阶段会多花时间细讲一下用到的技术细节: ES6 Babel 等


先有一个Pure JavaScript Lib的Hello World上手.
有了基本的认识之后,再根据框架内容讲改框架的代码如何模块化.
在讲如何对Pure JavaScript Lib的版本,使用构建工具进行构建.
最后的实际小组练手项目,在基于 构建工具+任务流的较为标准的项目结构下进行.

**Comment by yellowb** [comment]
那先把大纲确定下来，再估算每部分需要的时间，最后挑选要讲的内容并确定总时长要多久。这周末想找个时间**讨论下** （貌似违背了github这种异步非打扰式的工作方式，哈哈）。

**Comment by Aquariuslt** [comment]
@yellowb 好的

**Comment by yellowb** [comment]
（6天（week1 Mon~Fri）+（week2 Mon））
加上周末有8天
