### ISSUE TITLE
谁负责讲哪部分？

### ISSUE THREAD

**Issue by yellowb** [yellowb/full-stack-web-course#2]
MongoDB还是我来弄吧。

**Comment by Aquariuslt** [comment]
关于JavaScript Engineering这一部分

## 2017年课程提纲（修改中） ##
**时长: 1天**

|    章节（修改中）    | 备注 |
| ---------- | --- |
| (1)JS Modularize |  @Dantemo 来讲? |
| (2)Gulp  |   need update PPT |
| (3)Webpack|  need update PPT (注:webpack版本更新到2,PPT内容也会相对更新到2,且去掉大部分Demo.实际的Demo和Code会再下一个实战部分用到) |
| (4) Webpack Revolution 项目演练| 参考[Webpack Revolution](https://github.com/Aquariuslt/Webpack-Revolution)  预计用时:一个下午(这部分我讲) |

**Comment by yellowb** [comment]
DB：yellow
Node + express：Lance
Angular：Marquis
Engineering：Jason & Dante
small project：？（看到时谁比较有时间）
