### ISSUE TITLE
前端讲AngularJS还是Vue.js?

### ISSUE THREAD

**Issue by yellowb** [yellowb/full-stack-web-course#3]
前端讲AngularJS还是Vue.js?

**Comment by elathen** [comment]
个人认为AngularJS和Vue.js都讲
AngularJS目前我们好几个项目在用，用的版本是1.*，所以我们主要讲AngularJS 1.*, AngularJS 2.0 变化太大，在和其他框架对比，目前行业的接受度没有Vue.js高，公司目前也没有用的计划，所以目前不关注
Vue.js是去年行业采用度高的一个前端框架，我们公司已经有产品采用了，未来新的Model-2项目也有机会采用

综合上面2点，建议AngularJS 1.*和Vue.js都讲，对比着讲。

**Comment by yellowb** [comment]
那么课时需要得比较多，另外怕听众一次过学2种会搞混了...

**Comment by elathen** [comment]
如果这样，课程设计包括AngularJS和Vue.js，具体讲以那个为主，我们之后看公司的项目情况和方向再定。

**Comment by yellowb** [comment]
AngularJS的课件已经有了, 而且我看内容还挺全的, 那再准备下Vue.JS的

**Comment by humaruis** [comment]
同时讲两种，估计会懵逼

**Comment by jimrock** [comment]
如果公司方向以后偏向于用Vue的话就着重讲Vue吧，Angular可以做一些简单的介绍以及和Vue的对比即可。

**Comment by yellowb** [comment]
上次讨论过暂定ITA这个月还是讲angular 1，VueJS等组内share做完之后再放到ITA做。
