### ISSUE TITLE
Node.js要不要增加关于ES6语法的一些东西？

### ISSUE THREAD

**Issue by yellowb** [yellowb/full-stack-web-course#9]
主要是关系到后面的vue、webpack之类，因为网络上搜索到的资料大多是ES6语法写的，为了方便他们以后自己查资料。
@Lance，有什么看法？现在新做的项目用的是node.js什么版本？
@Aquariuslt ，你打算讲babel相关的东西吗？

**Comment by Aquariuslt** [comment]
@yellowb 有打算讲ES6语法.
大概是 ES5-ES6标准进化历史->浏览器支持情况-> Babel的简介以及其作用
最后结合Webpack 那部分讲一些:以ES6语法编写前端JavaScript, webpack的babel-loader转译,打包成浏览器可识别的ES5语法的Demo.

**Comment by yellowb** [comment]
@Aquariuslt 好啊，那我跟@Lance看看是不是在node.js这部分加点es6。不过不知道之前JavaWeb的课会不会也讲。。。= =

**Comment by lance4git** [comment]
了解了下，现在有项目在用v7.6.0的Node.js了（最新是v7.9.0）, 而且号称99%支持ES6，按趋势来看，考虑讲ES6.

**Comment by yellowb** [comment]
不知道前面第一个月的JavaWeb讲的JS讲到什么程度... @elathen 现在有这方面的资料吗? 就是外部vender的课表

**Comment by yellowb** [comment]
今天据 @elathen 所说，头一个月外部培训的课程讲JS大几率是讲ES5（没确定），所以我们可以准备一点ES6的内容在Node.js这部分课程里面。
